### PR TITLE
fix: add missing fsgroup option otherwise etcd couldn't read the dataDir

### PR DESCRIPTION
**Pull request by cwrau**

### CODE REVIEW

**Comment by jnummelin** [comment]
@cwrau The linter is not happy, could you have a look?

**Comment by Schnitzel** [comment]
btw, I'm running into exact same issue, just for me it works with `fsGroup: 0` but `fsGroup: 1001` should also work.

I'm confused though why tests previously passed without this, as I can't get it running unless this is set.

**Review by makhov — APPROVED** [review]

**Comment by makhov** [comment]
Thanks for the contribution!

**Comment by makhov** [comment]
@Schnitzel We use [rancher/local-path-provisioner](https://github.com/rancher/local-path-provisioner) in our tests and it runs ` mkdir -m 0777 -p "$VOL_DIR"` on volume provisioning. 
I'm thinking about switching to [openebs/dynamic-localpv-provisioner](https://github.com/openebs/dynamic-localpv-provisioner) for our tests

**Comment by cwrau** [comment]
@makhov sorry, I was on holiday, thanks for taking care of this 😅

Great that this got addressed so quickly!

**Pull request merged**
